# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.base.jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh', models.CharField(max_length=30, unique=True, verbose_name='\u4e2d\u6587\u6807\u7b7e')),
            ],
        ),
        migrations.CreateModel(
            name='UiResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u6807\u9898')),
                ('dsp', models.TextField(blank=True, verbose_name='\u8d44\u6e90\u63cf\u8ff0')),
                ('rs_dl_urls', helpers.base.jsonfield.JsonField(blank=[], verbose_name='\u8d44\u6e90\u4e0b\u8f7d\u5217\u8868')),
                ('rs_show', models.CharField(blank=True, max_length=500, verbose_name='\u8d44\u6e90\u5c55\u793a\u56fe\u7247')),
                ('resolution', models.CharField(choices=[('300x300', '300x300')], default='300x300', max_length=50, verbose_name='\u5c55\u793a\u5206\u8fa8\u7387')),
                ('added_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('tags', models.ManyToManyField(to='ui_rs.Tag', verbose_name='\u6807\u7b7e')),
            ],
        ),
    ]
